"""add name column to clothings table

Revision ID: 18ece93db1ac
Revises: 4c655d75eacf
Create Date: 2023-12-07 15:49:41.938226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18ece93db1ac'
down_revision = '4c655d75eacf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clothings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    with op.batch_alter_table('customs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_customs_clothing_id_customs', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_customs_clothing_id_clothings'), 'clothings', ['clothing_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_customs_clothing_id_clothings'), type_='foreignkey')
        batch_op.create_foreign_key('fk_customs_clothing_id_customs', 'customs', ['clothing_id'], ['id'])

    with op.batch_alter_table('clothings', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
