"""add price column to clothings

Revision ID: 3e4a9c9ed66b
Revises: 18ece93db1ac
Create Date: 2023-12-07 23:28:21.252222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e4a9c9ed66b'
down_revision = '18ece93db1ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clothings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clothings', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
