"""user, custom, clothing, blog models

Revision ID: 4c655d75eacf
Revises: 
Create Date: 2023-12-07 01:56:26.696261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c655d75eacf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blogs'))
    )
    op.create_table('clothings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('inseam', sa.Float(), nullable=True),
    sa.Column('chest', sa.Float(), nullable=True),
    sa.Column('waist', sa.Float(), nullable=True),
    sa.Column('hips', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clothings'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('customs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('clothing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clothing_id'], ['customs.id'], name=op.f('fk_customs_clothing_id_customs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_customs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customs'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customs')
    op.drop_table('users')
    op.drop_table('clothings')
    op.drop_table('blogs')
    # ### end Alembic commands ###
