"""add stripe price id column to clothings table

Revision ID: 602314e2881c
Revises: 68c8befab816
Create Date: 2024-01-16 11:44:42.940789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602314e2881c'
down_revision = '68c8befab816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clothings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_price_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clothings', schema=None) as batch_op:
        batch_op.drop_column('stripe_price_id')

    # ### end Alembic commands ###
