"""add purchased column to customs


Revision ID: 68c8befab816
Revises: db387cee2e8f
Create Date: 2024-01-03 14:14:06.683501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c8befab816'
down_revision = 'db387cee2e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchased', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customs', schema=None) as batch_op:
        batch_op.drop_column('purchased')

    # ### end Alembic commands ###
