"""add image path table

Revision ID: c96f8581c5f3
Revises: 3e4a9c9ed66b
Create Date: 2023-12-29 14:15:04.778489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c96f8581c5f3'
down_revision = '3e4a9c9ed66b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clothing_image_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('clothing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clothing_id'], ['clothings.id'], name=op.f('fk_clothing_image_paths_clothing_id_clothings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clothing_image_paths'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clothing_image_paths')
    # ### end Alembic commands ###
